# Build settings
defaults:
  -
    scope:
      path: "images/thumbnails/engagement"
    values:
      engagement: true
sass:
  sass_dir: _scss
  style: compressed

wedding_date: 'March 31 2019'
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

exclude:
  - yarn.lock
